package QuanLyThucUongg;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguyenkhactrung
 */
public class QuanLyThucUong extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    int currentPos = -1;
    List<ThucUong> List = new ArrayList<>();

    /**
     * Creates new form QuanLyThucUong
     */
    public QuanLyThucUong() {
        initComponents();

        tableModel = (DefaultTableModel) tb.getModel();

        showThucUong();
        tb.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                currentPos = tb.getSelectedRow();
                
                
                txtMaThucUong.setText(List.get(currentPos).getId() + "");
                txtTenThucUong.setText(List.get(currentPos).getTenThucUong());
                txtTenLoaiThucUong.setText(List.get(currentPos).getLoaiThucUong());
                txtDonViTinh.setText(List.get(currentPos).getDonViTinh());
                txtSoLuong.setText(List.get(currentPos).getSoLuong() + "");
                txtDonGia.setText(List.get(currentPos).getDonGia() + "");

            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
    }

    private void showThucUong() {
        List = ThucUongModify.findAll();

        tableModel.setRowCount(0);

        List.forEach((thucuong) -> {
            tableModel.addRow(new Object[]{thucuong.getId(), thucuong.getTenThucUong(),
                thucuong.getLoaiThucUong(), thucuong.getDonViTinh(), thucuong.getSoLuong(), thucuong.getDonGia()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenThucUong = new javax.swing.JTextField();
        txtTenLoaiThucUong = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtDonViTinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        FindByName = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaThucUong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ THỨC UỐNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N

        jLabel2.setText("Tên thức uống");

        jLabel3.setText("Đơn vị tính ");

        jLabel4.setText("Số lượng");

        jLabel5.setText("Đơn giá");

        jLabel6.setText("Tên loại thức uống");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Thoát");

        Insert.setText("THÊM");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Update.setText("SỬA");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        FindByName.setText("TÌM KIẾM");
        FindByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindByNameActionPerformed(evt);
            }
        });

        Delete.setText("XOÁ");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        reset.setText("LÀM MỚI");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã thức uống");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenThucUong)
                            .addComponent(txtTenLoaiThucUong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaThucUong))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Insert, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(68, 68, 68)
                        .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(FindByName, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                    .addComponent(txtSoLuong)
                    .addComponent(txtDonViTinh)
                    .addComponent(txtDonGia))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenLoaiThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert)
                    .addComponent(Update)
                    .addComponent(Delete)
                    .addComponent(FindByName)
                    .addComponent(reset))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã thức uống", "Tên thức uống", "Loại thức uống", "Đơn vị tính", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:

        int maThucUong = Integer.parseInt(txtMaThucUong.getText());
        String tenThucUong = txtTenThucUong.getText();
        String loaiThucUong = txtTenLoaiThucUong.getText();
        String donViTinh = txtDonViTinh.getText();
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        double donGia = Double.parseDouble(txtDonGia.getText());

        ThucUong thucuong = new ThucUong(maThucUong, tenThucUong, loaiThucUong, donViTinh, soLuong, donGia);

        ThucUongModify.insert(thucuong);

        showThucUong();
        JOptionPane.showMessageDialog(rootPane, "Lưu dữ liệu thành công!!!");
    }//GEN-LAST:event_InsertActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:

        txtMaThucUong.setText("");
        txtTenThucUong.setText("");
        txtTenLoaiThucUong.setText("");
        txtSoLuong.setText("");
        txtDonViTinh.setText("");
        txtDonGia.setText("");

    }//GEN-LAST:event_resetActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tb.getSelectedRow();
        if (selectedIndex >= 0) {
            ThucUong std = List.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xoá thức uống này?");
            System.out.println("option : " + option);

            if (option == 0) {
                ThucUongModify.delete(std.getId());
                showThucUong();
            }
        }
        txtMaThucUong.setText("");
        txtTenThucUong.setText("");
        txtTenLoaiThucUong.setText("");
        txtSoLuong.setText("");
        txtDonViTinh.setText("");
        txtDonGia.setText("");
        JOptionPane.showMessageDialog(rootPane, "Xoá thành công!!!");
    }//GEN-LAST:event_DeleteActionPerformed

    private void FindByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindByNameActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên thức uống cần tìm:");
        if (input != null && input.length() > 0) {
            List = ThucUongModify.findByFullname(input);

            tableModel.setRowCount(0);

            List.forEach((thucuong) -> {
                tableModel.addRow(new Object[]{thucuong.getId(), thucuong.getTenThucUong(),
                    thucuong.getLoaiThucUong(), thucuong.getDonViTinh(), thucuong.getSoLuong(), thucuong.getDonGia()});
            });
        } else {
            showThucUong();
        }
        JOptionPane.showMessageDialog(rootPane, "Tìm kiếm thành công!!!");
    }//GEN-LAST:event_FindByNameActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:x   

        if (currentPos >= 0) {

            List.get(currentPos).setId(Integer.parseInt(txtMaThucUong.getText()));
            List.get(currentPos).setTenThucUong(txtTenThucUong.getText());
            List.get(currentPos).setLoaiThucUong(txtTenLoaiThucUong.getText());
            List.get(currentPos).setDonViTinh(txtDonViTinh.getText());
            List.get(currentPos).setSoLuong(Integer.parseInt(txtSoLuong.getText()));
            List.get(currentPos).setDonGia(Double.parseDouble(txtDonGia.getText()));

            ThucUongModify.update(List.get(currentPos));
            currentPos = -1;
        } else {
            ThucUong t = new ThucUong(
                    Integer.parseInt(txtMaThucUong.getText()),
                    txtTenThucUong.getText(),
                    txtTenLoaiThucUong.getText(),
                    txtDonViTinh.getText(),
                    Integer.parseInt(txtSoLuong.getText()),
                    Double.parseDouble(txtDonGia.getText())
            );
            ThucUongModify.insert(t);
            List = ThucUongModify.findAll();
        }
        showThucUong();
        JOptionPane.showMessageDialog(rootPane, "Cập nhật dữ liệu thành công!!!");
        txtMaThucUong.setText("");
        txtTenThucUong.setText("");
        txtTenLoaiThucUong.setText("");
        txtSoLuong.setText("");
        txtDonViTinh.setText("");
        txtDonGia.setText("");

    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThucUong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton FindByName;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtMaThucUong;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenLoaiThucUong;
    private javax.swing.JTextField txtTenThucUong;
    // End of variables declaration//GEN-END:variables
}
